version: "3"

services:
  backend:
    build:
      context: .
      args:
        - WITH_XDEBUG=true
    depends_on:
      - database
    volumes:
      - .:/var/www
    entrypoint: /var/www/bootstrap.dev.sh
    environment:
    - XDEBUG_CONFIG=remote_host=172.17.0.1
    - APP_ENV=dev
    - DATABASE_URL=pgsql://test:qwerty@database:5432/user_management
    - PHP_OPCACHE=0

  nginx:
    image: nginx
    depends_on:
      - backend
    volumes:
      - ./nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 8888:80
    environment:
      - APP_ENTRYPOINT=/var/www/public/index.php
      - FPM_UPSTREAM=backend:9000

  database:
    image: postgres:9.6-alpine
    ports:
      - 5433:5432
    environment:
    - POSTGRES_USER=test
    - POSTGRES_PASSWORD=qwerty
    - POSTGRES_DB=user_management